#spring.application.name=FranchiseService
#
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=2;encrypt=true;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=${DB_PASSWORD:12345}
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.main.allow-circular-references=true
#
#server.address=0.0.0.0
#server.port=8080
#
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui/index.html
#springdoc.swagger-ui.disable-swagger-default-url=true
#
##JWT
#jwt.public-key=
#jwt.private-key=
#jwt.access-token-exp-minutes=15
#jwt.refresh-token-exp-days=7
#
##REDIS
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#
## Active profile
## deploy thì set SPRING_PROFILES_ACTIVE=prod ? môi tr??ng production, còn local thì set SPRING_PROFILES_ACTIVE=dev
#spring.profiles.active=dev
#
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [${spring.application.name:}] [requestId:%X{requestId}] %logger - %msg%n