server:
  port: ${PORT:8081}

spring:
  application:
    name: csfc-auth-service

  datasource:
    # Railway MySQL (hardcode)
    url: jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: jkuIcnzTlPiQfVdyrqaXrBWAoTuXWdnr
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 60000
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: tuldse184668@fpt.edu.vn
    password: fryzapjrxznpmkyc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: https://microservice-6dyb.onrender.com/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: V7Pz0c5ZmTz4IVBdBrgiapaNOSKpRDWtT8AsXm+C1mE=
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
  health:
    defaults:
      enabled: true
