
server.address=0.0.0.0
server.port=8763

spring.application.name=metadata-service


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true


spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=metadata_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=${DB_PASSWORD:12345}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


spring.cache.type=redis
spring.cache.redis.time-to-live=30000
spring.cache.redis.cache-null-values=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


spring.data.redis.host=localhost
spring.data.redis.port=6379

metadata.key.pattern=^[a-zA-Z_][a-zA-Z0-9_.]*$


management.endpoints.web.exposure.include=health,info


logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [${spring.application.name:}] [requestId:%X{requestId}] %logger - %msg%n