spring.application.name=shift-service
server.port=${PORT:8081}
spring.output.ansi.enabled=always

# Cau hinh ket noi PostgreSQL (Render)
spring.datasource.url=jdbc:postgresql://dpg-d6ntij15pdvs73ftol50-a/shift_db_lqv6
spring.datasource.username=shift_db_lqv6_user
spring.datasource.password=i2CnAvRHtzNgXtf63QCQnvkKiDH4JyGx
spring.datasource.driver-class-name=org.postgresql.Driver

# Cau hinh Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cau hinh Eureka Client
eureka.client.service-url.defaultZone=https://microservice-6dyb.onrender.com/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.uuid}